<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fku_people"
 *
 * Auto generated by Extension Builder 2014-07-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'FKU People',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Widmer',
	'author_email' => 'daniel.widmer@fku.ch',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '6.1.0',
	'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-10.4.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];

/******************************************
 * Version 2.4.2
 * -------------
 * Fehler bei Eingabekontrolle behoben ($vorname und $nachname geprüft statt nur $name für $error = 3
 *
 * Version 2.4.3
 * -------------
 * Added personRespository function FindByFullName
 *
 * Version 2.4.4
 * -------------
 * New field txFkupeoplePlanningcal in feuser for EXT:fku_planning
 *
 * Version 2.5.0
 * -------------
 * Notification functionality (new tables, new fields in feuser table)
 * New view: dashboard
 *
 * Version 2.5.1
 * -------------
 * Bug in PersonController->showAction: deleted ->getFirst()
 *
 * Version 2.6.0
 * -------------
 * Added column tx_fkupeople_planning_alarm to table fe_users
 *
 * Version 2.6.1
 * -------------
 * Default sorting in personRepository by name
 *
 * Version 3.0.0
 * -------------
 * Initial implementation notifications
 *
 * Version 3.0.1
 * -------------
 * Separation of initial information about e-mail address, new action notificationInfo added
 *
 * Version 3.0.2
 * -------------
 * New partial layout files for notifications
 * setup.txt mit templateRootPaths instead of templateRootPath
 *
 * Version 3.1.0
 * -------------
 * New password generator
 *
 * Version 3.1.1
 * -------------
 * Multiple categories per notification rule now works
 *
 * Version 3.1.2
 * -------------
 * Changing timing per notification now works
 * Notifiation repository to find some specific notifications per user
 *
 * Version 3.2.0
 * -------------
 * Filtering categories for new notifications
 *
 * Version 3.2.1
 * -------------
 * Text in NotificationsInfo dependent on e-mail address
 * FlashMessages and alerts with icons
 *
 * Version 3.2.2
 * -------------
 * Minor correction in notification e-mail text creation
 *
 * Version 3.3.0
 * -------------
 * Updates in TCA definition for table person
 * New action to show team list (teamAction)
 *
 * Version 4.0.0
 * -------------
 * Controller NotificationCommandController takes over notification storage and e-mailing of other extensions
 *
 * Version 4.0.1
 * -------------
 * Removed Template Team/List.html
 * Disabled escapeOutput in Dayselection viewhelper
 * File name generatePassword.html -> GeneratePassword.html
 *
 * Version 4.0.2
 * -------------
 * Minor change in NotificationInfo partial view
 *
 * Version 4.1.0
 * -------------
 * Constant / Setup that allows to block all notification e-mails to be sent
 * New function findAllPerRule in NotificationRepository
 *
 * Version 4.1.1
 * -------------
 * Minor changes in PersonController line 319 and in NotificationCommandController line 197-200 to fix bugs
 *
 * Version 4.1.2
 * -------------
 * Mail to daniel.widmer@dotter.ch in case $notificationTexts is not an array in NotificationCommandController
 *
 * Version 5.0.0
 * -------------
 * Added SeniorBirthday view
 * Simplified alert display, dismissable OK-alert
 * Added birthday table in SQL plus definition in TCA, model, repository, language file
 * Tidied up language files
 *
 * Version 5.1.0
 * -------------
 * Update of notification settings and number of days via AJAX using eID
 * Exiseting notification with buttons and button groups instead of links
 *
 * Version 5.1.1
 * -------------
 * Minor update in Partials>Person>PropertiesList by adding &nbsp;
 * Correct age calcuation in PersonController->SeniorBirthdayAction
 *
 * Version 5.1.2
 * -------------
 * Fixed issue with synchronization scheduler task
 *
 * Version 5.1.3
 * -------------
 * PasswordGenerator form allows more and longer passowrds
 *
 * Version 5.1.4
 * -------------
 * Add more actions in non-cacheable actions in ext_localconf.php
 *
 * Version 5.2.0
 * -------------
 * Applied corrections in TCA definitions based on depreciated functions
 *
 * Version 6.0.0
 * -------------
 * Ready for Typo3 version 10, Bootstrap 4.5, Glyphicons 2.4
 *
 * Version 6.0.1
 * -------------
 * Apply constanct "notificationBlocker" also to birthday e-mails, not only notifications
 * Corrections in sending birthday e-mails
 *
 * Version 6.0.2
 * -------------
 * Added composer.json
 * Correction in NotificationCommand.php
 *
 * Version 6.0.3
 * -------------
 * Added using persistence manager in NotificationCommand
 *
 * Version 6.0.4
 * -------------
 * Use setlocale in BirthdayCommand to get weekdays in German
 *
 * Version 6.0.5
 * -------------
 * Corrections in SyncCommand
 * Minor update in BirthdayCommand for return values
 *
 * Version 6.1.0
 * -------------
 * Added use of Notification model in PersonController
 * Replaced eID concept by middleware (PSR-15) concept, also adapting partial template NotificationExisting.html
 * Removed TypeScript mod.fe_users.txt and hence changed ext_localconf.php
 *
 *
 */